CREATE TABLE review_photos (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  review_id INT REFERENCES review(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  path VARCHAR(500) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
