CREATE TABLE review (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id INT REFERENCES project(id),
  created_by INT REFERENCES member(id),
  doc_code VARCHAR(50),
  review_date TIMESTAMP,
  responsible VARCHAR(100),
  normativa_asme_b313 BOOLEAN,
  normativa_asme_b314 BOOLEAN,
  normativa_api_650 BOOLEAN,
  normativa_api_1104 BOOLEAN,
  normativa_aws_d11 BOOLEAN,
  technical_spec TEXT,
  drawings TEXT,
  deviation_description TEXT,
  corrective_actions TEXT,
  review_status VARCHAR(50) CHECK (review_status IN ('open', 'closed', 'viewed')),
  comments TEXT,
  conclusion TEXT,
  inspector_name VARCHAR(100),
  jt_sup_name VARCHAR(100),
  adc_name VARCHAR(100),
  client_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
